spring.application.name=consulta-reemplacamiento-ms
spring.jpa.properties.hibernate.jdbc.time_zone=America/Lima
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss.SSS
spring.jackson.time-zone=America/Lima

#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

spring.profiles.active=${DEPLOY}
server.port=10110

server.servlet.context-path=/api
